version: 0.0

os: linux

files:
  - source: /
    destination: /root/misskey-deployment

permissions:
  - object: scripts
    pattern: "**"
    mode: 755

hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180

  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 180
