version: "3"

services:
  nginx:
    container_name: "nginx"
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - $HOME/data/certbot/conf:/etc/letsencrypt
      - $HOME/data/certbot/www:/var/www/certbot

  certbot:
    container_name: "certbot"
    image: certbot/certbot:latest
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - $HOME/data/certbot/conf:/etc/letsencrypt
      - $HOME/data/certbot/www:/var/www/certbot


