on:
  push:
    branches: [ "main" ]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: |
          echo "Hello world!"
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup AWS credential
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ap-northeast-2

      - name: Upload S3
        run: |
          aws s3 sync . s3://misskey-deployment

      - name: CodeDeploy
        run: |
          aws deploy create-deployment \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --application-name misskey \
          --deployment-group-name misskey \
          --github-location repository=integraldx/misskey-deployment,commitId=${{ github.sha }}
          